apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-api
  template:
    metadata:
      labels:
        app: ml-api
    spec:
      containers:
      - name: ml-api-container
        # This is a placeholder that the CI/CD workflow will replace
        image: IMAGE_PLACEHOLDER
        ports:
        - containerPort: 8000